### ISSUE TITLE
implement privileged spec v1.12 features

### ISSUE THREAD

**Issue by strichmo** [openhwgroup/core-v-verif#1027]
### Task Outcome
The core-v-verif testbench infrastructure is updated to verify the CV32E40X core against the planned RISCV Privileged v0.12 Specification implementation.

### Background information
The CV32E40X will now support the CSRs within the RISCV v1.12 Privileged Specification.  Note that the User Manual for the cv32e40x will give more detailed descriptions of the extent of support for optional CSRs.  The CV32E40X will still only support machine-mode.

### Completion Criteria
The RTL is updated with all planned cv32e40x 0.12 privileged specification updates and the testbench passes a release check regression.

The core-v-verif common core control infrastructure should be updated to support selectively configuring a core for 1.11 or 1.12 specifications.  This will mostly affect a mode switch to the ISS used.

**Comment by silabs-hfegran** [comment]
Resolved
