### ISSUE TITLE
make clean does not clean firmware directories

### ISSUE THREAD

**Issue by GTumbush** [openhwgroup/core-v-verif#103]
### Steps to Reproduce
git clone https://github.com/openhwgroup/core-v-verif
cd core-v-verif/cv32/sim/uvmt_cv32
make clean

## To get the sandbox back into the same state as when it was checked out the following steps are required:
make clean_core_tests
make clean_test_programs
make clean SIMULATOR=<simulator version>

@eroom1966 @MikeOpenHWGroup

**Comment by MikeOpenHWGroup** [comment]
Agreed.  That is what `clean_all` does.

**Comment by GTumbush** [comment]
Verified with Lee that this is OK.
