### ISSUE TITLE
c-code tests using EXIT_FAILURE results in a test passing

### ISSUE THREAD

**Issue by silabs-PaulZ** [openhwgroup/core-v-verif#107]
In the UVM test bench, a type 1 test program that uses `return EXIT_FAILURE;` returns a simulation passing status. The core testbench correctly shows a test error.

as seen in https://github.com/openhwgroup/core-v-verif/blob/ca9315a9f98e606ab8f3c6de3b52d8ffe361fe20/cv32/tests/core/custom/hello_world.c#L44

**Comment by strichmo** [comment]
This was cleaned up with this pull request.  It has been verified that returning EXIT_FAILURE will cause a UVM failure.

https://github.com/openhwgroup/core-v-verif/pull/178
