### ISSUE TITLE
Refactoring for the CV32E40X test-program definitions

### ISSUE THREAD

**Issue by MikeOpenHWGroup** [openhwgroup/core-v-verif#1107]
### Task Outcome
Removal of all deprecated toolchain selection parameters in the test-program definitions for the CV32E40X.

### Background information
As documented in the toolchain selection sub-section of the [TOOLCHAIN](https://github.com/openhwgroup/core-v-verif/blob/cv32e40x/dev/mk/TOOLCHAIN.md#toolchain-selection) markdown, there exists a set of YAML files that are used as individual and group test-program definitions.  After the merge of #1092, many of the toolchain selection parameters in these test-program definitions are deprecated and should be removed.

### Location Information
Per-test-program definitions are in `$CORE_V_VERIF/cv32e40x/tests/programs/<custom|corev-dv>/<test-program-name>/default.yaml`.
Group test-program definitions are in `$CORE_V_VERIF/cv32e40x/tests/cfg/*.yaml`.

### Completion Criteria
Remove all references to deprecated toolchain selection parameters and replace them with toolchain selection parameters of the form `CV_SW_*`.   Examples of deprecated toolchain selection parameters:
```
riscv_march: rv32imc_zba0p93_zbb0p93
gnu_march:   rv32imc_zba0p93_zbb0p93
corev_march: rv32imc_zba1p00_zbb1p00_zbc1p00
llvm_march:  rv32imc_zba1p00_zbb1p00_zbc1p00_zbs1p00
```

**Comment by silabs-hfegran** [comment]
This has been removed, closing task
