### ISSUE TITLE
Toolchain makefile variables break Verissimo integration

### ISSUE THREAD

**Issue by gabrielrad** [openhwgroup/core-v-verif#1149]
When invoking `make create_dvt_build_file` from `core-v-verif/cv32e40p/sim/uvmt` directory, to create the build file needed by Verissimo in order to compile the project we get:

> core-v-verif/mk/Common.mk:83: Must define a DPI_DASM_SPIKE_REPO to use the common makefile
> core-v-verif/mk/Common.mk:253: *** CV_SW_TOOLCHAIN not defined in either the shell environment, test.yaml or cfg.yaml.  Stop.

**Comment by MikeOpenHWGroup** [comment]
HI @gabrielrad, I have pushed in a fix on the `master`, `cv32e40p/dev` and `cv32e40p/release` branches.  The Verissimo build and run on `dev` works as expected, but `master` and `release` fail to build.  The changes to the Makefile are identical.   Can you have a look?

**Comment by gabrielrad** [comment]
The `Common.mk` file is different between master and dev. On master it fails with:

> /home/gabriel.raducan/core-v-verif/mk/Common.mk:83: Must define a DPI_DASM_SPIKE_REPO to use the common makefile
/home/gabriel.raducan/core-v-verif/mk/Common.mk:253: *** CV_SW_TOOLCHAIN not defined in either the shell environment, test.yaml or cfg.yaml.  Stop.

**Comment by gabrielrad** [comment]
That is `dvt.mk`, not `Common.mk`. It passes on dev because that version of `Common.mk` is lacking those error macros.

In `Common.mk` the `dvt.mk` is included after the check for `CV_SW_TOOLCHAIN`.

**Comment by MikeOpenHWGroup** [comment]
Ah, _now_ I see.

This has exposed a flaw in our branch management flow.   That is a different problem, but I think I see a simple fix for this issue (that also won't get in the way of the branch management problem).

I'd like to be able to test this myself - what is the command-line you use to run Verissimo?  I do not need to actually run Verissimo locally, all I want to so is ensure that the Makefiles will produce a proper invocation.

**Comment by gabrielrad** [comment]
You need to go to `cv32e40p/sim/uvmt` and run `make create_dvt_build_file` and this should create a `core-v-verif/.dvt/default.build` file. 

Could we make this check available on all Pull Request in the future, similar to licensing?

**Comment by MikeOpenHWGroup** [comment]
> You need to go to cv32e40p/sim/uvmt and run make create_dvt_build_file and this should create a core-v-verif/.dvt/default.build file.

I have manually run this on the head of the `master`, `cv32e40p/dev` and `cv32e40p_release` branches.  The results were the same each time.  First the Makefile issues the following to stdout:
```
/home/mike/GitHubRepos/openhwgroup/core-v-verif/master/mk/Common.mk:83: Must define a DPI_DASM_SPIKE_REPO to use the common makefile
/home/mike/GitHubRepos/openhwgroup/core-v-verif/master/mk/Common.mk:278: CV_SW_MARCH not defined in either the shell environment, test.yaml or cfg.yaml
/home/mike/GitHubRepos/openhwgroup/core-v-verif/master/mk/Common.mk:291: CV_SW_CC not defined in either the shell environment, test.yaml or cfg.yaml
/home/mike/GitHubRepos/openhwgroup/core-v-verif/master/mk/Common.mk:303: CV_SW_CFLAGS not defined in either the shell environment, test.yaml or cfg.yaml
/home/mike/GitHubRepos/openhwgroup/core-v-verif/master/mk/Common.mk:318: RISCV set to /opt/riscv
/home/mike/GitHubRepos/openhwgroup/core-v-verif/master/mk/Common.mk:319: RISCV_PREFIX set to riscv32-unknown-elf-
/home/mike/GitHubRepos/openhwgroup/core-v-verif/master/mk/Common.mk:320: RISCV_EXE_PREFIX set to /opt/riscv/bin/riscv32-unknown-elf-
/home/mike/GitHubRepos/openhwgroup/core-v-verif/master/mk/Common.mk:321: RISCV_MARCH set to rv32imc
/home/mike/GitHubRepos/openhwgroup/core-v-verif/master/mk/Common.mk:322: RISCV_CC set to gcc
/home/mike/GitHubRepos/openhwgroup/core-v-verif/master/mk/Common.mk:323: RISCV_CFLAGS set to 
```
The above is what I would expect.  Next, the following `.dvt/default.build` is generated:
```
+dvt_enable_elaboration +dvt_enable_elaboration_incremental+FULL +dvt_init+dvt -uvm	+define+CV32E40P_ASSERT_ON +define+ISS+CV32E40P_TRACE_EXECUTION +incdir+/home/mike/GitHubRepos/openhwgroup/core-v-verif/master/cv32e40p/env/uvme +incdir+/home/mike/GitHubRepos/openhwgroup/core-v-verif/master/cv32e40p/tb/uvmt -f /home/mike/GitHubRepos/openhwgroup/core-v-verif/master/core-v-cores/cv32e40p/cv32e40p_manifest.flist -f /home/mike/GitHubRepos/openhwgroup/core-v-verif/master/cv32e40p/tb/uvmt/uvmt_cv32e40p.flist -f /home/mike/GitHubRepos/openhwgroup/core-v-verif/master/cv32e40p/tb/uvmt/imperas_iss.flist -top uvmt_cv32e40p_tb
```

Is this _not_ what is expected?  What does a successful run of `make create_dvt_build_file` look like?

> Could we make this check available on all Pull Request in the future, similar to licensing?

That is a good idea.  Yes, we can do this.

**Comment by gabrielrad** [comment]
#1198

**Comment by MikeOpenHWGroup** [comment]
Hi @gabrielrad, I believe this issue is resolved for now.  Please confirm and close this issue if you agree.

**Comment by gabrielrad** [comment]
@MikeOpenHWGroup the issue has been fixed! Thanks!
