### ISSUE TITLE
User-mode vplan review, cv32e40s

### ISSUE THREAD

**Issue by silabs-robin** [openhwgroup/core-v-verif#1256]
### Task Outcome
The attached 40s vplan for user-mode is reviewed, revised, accepted, and pushed to the repo.

### Location Information
The spreadsheet is uploaded in this PR: https://github.com/openhwgroup/core-v-verif/pull/1287.
~~The [pre-review] vplan is downloadable from here: [CV32E40S_UserMode.xlsx](https://github.com/openhwgroup/core-v-verif/files/8571732/CV32E40S_UserMode.xlsx).~~
~~A PR will later place the final file at `core-v-verif/cv32e40s/docs/VerifPlans/Simulation/privileged_spec`.~~

### Completion Criteria
The review procedure is completed (as per [here](https://github.com/openhwgroup/core-v-verif/blob/master/docs/VerifPlans/VerificationPlanning101.md#verification-plan-reviews)) and the finished file is in the repo.

**Comment by silabs-robin** [comment]
_"Arrange for a review call for the verification plan"_
This can wait a bit, as we have more vplans coming up (PMP, CLIC, Zc), and it could be(?) more efficient to do them all at once or in close proximity.

**Comment by Silabs-ArjanB** [comment]
[CV32E40S_UserMode-Arjan.xlsx](https://github.com/openhwgroup/core-v-verif/files/8812069/CV32E40S_UserMode-Arjan.xlsx)

**Comment by MikeOpenHWGroup** [comment]
Is that #1287?
