### ISSUE TITLE
PMP vplan review, cv32e40s

### ISSUE THREAD

**Issue by silabs-robin** [openhwgroup/core-v-verif#1260]
### Task Outcome
The attached 40s vplan for PMP is reviewed, revised, accepted, and pushed to the repo.

### Location Information
The spreadsheet is uploaded in this PR: https://github.com/openhwgroup/core-v-verif/pull/1288.
~~The [pre-review] vplan is downloadable from here: [CV32E40S_PMP.xlsx](https://github.com/openhwgroup/core-v-verif/files/8647656/CV32E40S_PMP.xlsx)~~
~~A PR will later place the final file within `core-v-verif/cv32e40s/docs/VerifPlans/Simulation/`.~~

### Completion Criteria
The review procedure is completed (as per [here](https://github.com/openhwgroup/core-v-verif/blob/master/docs/VerifPlans/VerificationPlanning101.md#verification-plan-reviews)) and the finished file is in the repo.

**Comment by Silabs-ArjanB** [comment]
[CV32E40S_PMP-Arjan.xlsx](https://github.com/openhwgroup/core-v-verif/files/8812053/CV32E40S_PMP-Arjan.xlsx)

**Comment by silabs-robin** [comment]
We have had internal reviews and the vplan is being uploaded in a PR.
If no additional OpenHW-orchestrated review meeting is desired, then this issue can be closed.

**Comment by MikeOpenHWGroup** [comment]
Is that #1288?

**Comment by silabs-robin** [comment]
> Is that https://github.com/openhwgroup/core-v-verif/pull/1288?

Yes.
