### ISSUE TITLE
CVA6 arch tests are failing with latest riscof environment

### ISSUE THREAD

**Issue by spidugu444** [openhwgroup/core-v-verif#1283]
### Issue Description

HI

In latest  RISCOF CVA6 riscv-arch-tests tests are failing due to mismatch in between spike and verilator csv.
I used  [cva6_spike_log_to_trace_csv.py](https://github.com/10x-Engineers/core-v-verif/blob/8fc3143c3c14973e123bdb52a6c92f1ce9b1f115/cva6/sim/cva6_spike_log_to_trace_csv.py) script for spike log to csv conversion.
As shown below some lines are missing in spike csv which has been presented in spike log.

![Screenshot from 2022-05-31 17-52-29](https://user-images.githubusercontent.com/103561542/171173192-0c74a256-50f9-4625-8a6f-d4c497330ac0.png)

![image](https://user-images.githubusercontent.com/103561542/171174544-8e156754-42af-4f7a-b1a6-ba4fff6d66e8.png)

Note: I tried same scirpt for riscv-compliance-tests which is working fine.

please find the spike log and csv files attached below.

[addi-01.log](https://github.com/openhwgroup/core-v-verif/files/8805249/addi-01.log)
[addi-01.csv](https://github.com/openhwgroup/core-v-verif/files/8805250/addi-01.csv)

### Description of Done

Need help in resolving above issue.

**Comment by spidugu444** [comment]
@ASintzoff Please find the [setup](https://github.com/openhwgroup/core-v-verif/pull/1254) that I used to set RISCOF  dv-arch-test suite.

**Comment by umerimran-10xe** [comment]
@spidugu444 Please use the version 1.1.0 release of [Spike](https://github.com/riscv-software-src/riscv-isa-sim/releases/tag/v1.1.0 ). I think its because some stuff is updated in the master branch of riscv-isa-sim and we have not currently incorporated these changes in **cva6_spike_log_to_trace_csv.py** file. 
The Spike 1.1.0 version will resolve the problems related to RISCV-Arch tests mismatch as log is not generated according to how our log to csv trace works.

cc/ @fatimasaleem

**Comment by Imperas** [comment]
> In latest RISCOF CVA6 riscv-arch-tests tests are failing due to mismatch in between spike and verilator csv.

I am a little confused by the above statement. 

RISCOF is a python framework from RISC-V International Arch Test SIG that uses signature compare from the reference models to your DUT.  there is no CSV in RISCOF - are you confusing this with Google RISCV-DV which does a CSV and has scripts like log_to_trace_csv.py? 
Simon

**Comment by fatimasaleem** [comment]
> RISCOF is a python framework from RISC-V International Arch Test SIG that uses signature compare from the reference models to your DUT. there is no CSV in RISCOF - are you confusing this with Google RISCV-DV which does a CSV and has scripts like log_to_trace_csv.py?

Hi @Imperas 
Actually, We have not incorporated the RISCOF python framework in the core-v-verif infrastructure rather we have made some necessary changes to run the RISCOF compatible arch tests in the already existing verification environment of core-v-verif. We are running the latest arch-tests on spike and DUT, and comparing using the CSV. We are not using the sail as a reference model while running the arch tests in core-v-verif infrastructure.

**Comment by spidugu444** [comment]
with updated  version of spike issue got resolved and I am closing this issue.

**Comment by JeanRochCoulon** [comment]
Great !    @spidugu444 Could you indicate the Spike version which fails and the Spike version which passes ?  To avoid using the bad version !!

**Comment by spidugu444** [comment]
@JeanRochCoulon I faced issue while I was using commit id: e93b9cbbbcd3ad0a02ae298e9f1a2d98d3ac0153,but  with latest version [spike 1.1.0](https://github.com/riscv-software-src/riscv-isa-sim/releases/tag/v1.1.0) issue got resolved.
