### ISSUE TITLE
[TASK] Add riscv-arch-test suite to existing CVA6 core-v-verif CI (32-bit and 64-bit)

### ISSUE THREAD

**Issue by spidugu444** [openhwgroup/core-v-verif#1294]
### Is there an existing core-v-verif task for this?

- [X] I have searched the existing task issues

### Task Description

Adding riscv-arch-test suite for riscv cva6 environment.

Steps:
1.Please find the [setup](https://github.com/openhwgroup/core-v-verif/pull/1254) used to bring up cva6   riscv-arch-tests with the riscof-dev infrastructure
2.Need to update [spike](https://github.com/riscv-software-src/riscv-isa-sim/releases/tag/v1.1.0) version 1.1.0.

### Description of Done

perform CI run

**Comment by jquevremont** [comment]
PR submitted in Thales internal CI.

**Comment by jquevremont** [comment]
@ASintzoff provided feedback. Waiting for the fix.

**Comment by jquevremont** [comment]
Investigating too long simulation time.
@ASintzoff: need to check the trigger of the end of the simulation (instead of waiting for the timeout).

**Comment by jquevremont** [comment]
Now solved.
