### ISSUE TITLE
[TASK] Dashboard for CVA6 regression based on core-v-verif

### ISSUE THREAD

**Issue by yanicasa** [openhwgroup/core-v-verif#1296]
### Is there an existing core-v-verif task for this?

- [X] I have searched the existing task issues

### Task Description

Provide a way to have regression status when contributors submit a contribution via direct push or PR.
The regression description is public (core-v-verif repo) but runs on private infrastructure due to licensing restrictions.

### Description of Done

From a public perspective, the first step is for each submitted commit to populate the dashboard. (core-v-verif & cva6)

**Comment by yanicasa** [comment]
https://github.com/openhwgroup/core-v-verif/pull/1324

**Comment by yanicasa** [comment]
https://github.com/openhwgroup/core-v-verif/pull/1321

**Comment by jquevremont** [comment]
Status at today's meeting.
