### ISSUE TITLE
[TASK] CV-X-IF UVM agent for CVA6

### ISSUE THREAD

**Issue by ASintzoff** [openhwgroup/core-v-verif#1297]
### Is there an existing core-v-verif task for this?

- [X] I have searched the existing task issues

### Task Description

UVM agent behaving as a coprocessor with dedicated custom instructions

### Description of Done

Pass successfully CV-X-IF manual tests on CVA6

**Comment by jquevremont** [comment]
3 out of 6 CV-X-IF interfaces implemented.
New task to open for the outstanding 3 interfaces.
