### ISSUE TITLE
[TASK] CV-X-IF CVA6 verification

### ISSUE THREAD

**Issue by ASintzoff** [openhwgroup/core-v-verif#1299]
### Is there an existing core-v-verif task for this?

- [X] I have searched the existing task issues

### Task Description

Run randomly generated tests by core-dv (riscv-dv) using custom CV-X-IF instructions

### Description of Done

Pass successfully CV-X-IF random generated tests on CVA6

**Comment by MikeOpenHWGroup** [comment]
Hi @ASintzoff, when you say "Run random generated tests", do you mean test-programs randomly generated by corev-dv (riscv-dv)?

**Comment by jquevremont** [comment]
Work in progress. Verification stated on 3 out of 6 interfaces. Need to reveiw.

**Comment by jquevremont** [comment]
The task is tracked in the verification GANTT. Closing it here.
