### ISSUE TITLE
Move / port test cases and test infrastructure from cv32e40p repos

### ISSUE THREAD

**Issue by Silabs-ArjanB** [openhwgroup/core-v-verif#133]
As part of https://github.com/openhwgroup/cv32e40p/pull/387 various test cases and test infrastructure will be removed from the cv32e40p repos. 

This (or ported versions) need to be added back in the core-v-verif repos.

At this moment specifically the following are missing from core-v-verif:

tb/core/csmith
tb/core/custom_fp
tb/core/interrupt_test
cv32e40p/tb/dm 
cv32e40p/ci/run-openocd-compliance.sh

**Comment by MikeOpenHWGroup** [comment]
Now is a good time to be doing this as we are starting to see some stability and increased capability in the cv32e40p environment in [core-v-verif](https://github.com/openhwgroup/core-v-verif).  My thoughts on the specific directories you mentioned:
- **tb/core/csmith**: the use of [cmsith](https://embed.cs.utah.edu/csmith/) in RI5CY was an interesting experiment, but I do not use it driving coverage in RTL verifiction so it was deleted from core-v-verif some time ago and there are no plans to bring it back.  I recommend that it be removed from cv32e40p altogether.
- **tb/core/custom_fp**: these will not be used by core-v-verif, even when FP verification is on the plan.  Safe to remove.
- **tb/core/interrupt_test**: I have ported this to core-v-verif (just now).  I expect the testbench will need to be updated to support it.
- **cv32e40p/tb/dm**: this appears to be a simple testbench incorporating the RI5CY core and Pulp debug module.  It was determined by the TWG that the DM is beyond the scope of cv32e40p verification, so it was removed from core-v-verif.  Recommend it be removed from cv32e40p altogether.
- **cv32e40p/ci/run-openocd-compliance.sh**: there are no plans to do anything with OpenOCD in core-v-verif.  Safe to remove.

Given the above, I think we can close this issue.   You may want to create an equivalent issue for cv32e40p just to ensure that the Design team has a chance to comment.

**Comment by MikeOpenHWGroup** [comment]
Ha!   I just now saw https://github.com/openhwgroup/cv32e40p/pull/387.

We are all on the same page I think.

**Comment by MikeOpenHWGroup** [comment]
One last comment:  there is a [task](https://github.com/openhwgroup/core-v-verif/issues/87) in core-v-verif to complete the port of the interrupt tests.  This task is ready to start, and waiting for a Contributor to appear.

**Comment by Silabs-ArjanB** [comment]
Hi, I only think we have a verification hole with respect to DM / run-openocd-compliance.sh. Are we really going to leave that to the users of CV32E40P / CVA6?

**Comment by MikeOpenHWGroup** [comment]
My proposal to include the DM in the cv32e40p verification environment was rejected.   The decision was to maintain focus on the core in simulation/formal verification and cover the DM and CORE+DM interactions in the FPGA prototypes being developed by the HWTG.  We will need to be vigilant to ensure that the HWTG keeps this on their radar.

I completely agree that OpenOCD compliance testing should be done in an FPGA prototype, not RTL simulation.  Having said that, in the long term, I am expecting that RTL verification of the DM to come back to the VTG in due time.  :wink: It will probably be after RTL Freeze of the cv32e40p core.

**Comment by MikeOpenHWGroup** [comment]
Hi @Silabs-ArjanB, I believe this issue can be resolved as part of the original work has been completed and other parts are no longer relevant.   Let me know if you agree/disagree.

**Comment by Silabs-ArjanB** [comment]
Agreed. We also agreed to leave the debug module related verification out for now; I would like to re-discuss that after RTL freeze.
