### ISSUE TITLE
[TASK] Verification configuration

### ISSUE THREAD

**Issue by JeanRochCoulon** [openhwgroup/core-v-verif#1343]
### Is there an existing core-v-verif task for this?

- [X] I have searched the existing task issues

### Task Description

 We have to implement a process to control the testbench memory model addressing, test-program compile flags and the core configuation at compile and run-time.

Please read https://github.com/openhwgroup/core-v-verif/pull/1342 for more information

### Description of Done

Support the smae features than CV32E4 verification. @MikeOpenHWGroup could help validating the complation of the task.

**Comment by jquevremont** [comment]
Configurations defined. Not yet implemented.

**Comment by jquevremont** [comment]
Need to talk with @MikeOpenHWGroup to check the implementation is OK.

**Comment by jquevremont** [comment]
We are satisfied with the current flow for 1 CVA6 configuration.
