### ISSUE TITLE
CV32E40X: Running Custom tests

### ISSUE THREAD

**Issue by eroom1966** [openhwgroup/core-v-verif#1356]
@silabs-hfegran @silabs-mateilga 

I am currently looking at the transition to using ImperasDV, and I wanted to get a baseline set of results.
I checked out the CV32E40X/dev branch, and when running all of the custom tests the following fail when run against the ISS.

```
debug_test_trigger.log:                   SIMULATION FAILED - ABORTED              
mhpmcounter29_csr_access_test_2.log:                       SIMULATION FAILED                    
pma.log:                       SIMULATION FAILED                    
```

Is this expected behavior ?
command line is 

make CV_CORE=cv32e40x USE_ISS=YES TEST=<name> test

**Comment by silabs-hfegran** [comment]
Hi Lee, 
We are currently running all tests mentioned in core-v-verif/cv32e40x/regress/cv32e40x_full.yaml, any test not mentioned in that file or with a configuration that is not specified in that file are not in a state where they necessarily are expected to pass. 

On the top of my head, I know that the mhpmcounter29_csr_access_tests (both 1 and 2) needs to run with a config that sets the number of mhmpcounters to 29. (See cv32e40x/tests/cfg/num_mhpmcounter_29.yaml for details)

debug_test_trigger and pma are not currently in the full regression, and I am not aware of their current state.
