### ISSUE TITLE
Dead code in CVA6

### ISSUE THREAD

**Issue by AyoubJalali** [openhwgroup/core-v-verif#1375]
Hello, @JeanRochCoulon @ASintzoff 
While improving the CC of the CVA6 core processor, I notice there is a lot of lines related to the vector extension (V extension) in the id_stage.decoder module, as i know the CVA6 don’t support V extension, so there is any meaning of code that CVA6 can't execute at all ? or we can say it's a DEAD CODE.
 
![vv](https://user-images.githubusercontent.com/110232072/185412485-9b5d2456-a2fe-43f8-800d-547fe576c767.PNG)

**Comment by MikeOpenHWGroup** [comment]
Hi @AyoubJalali, thanks for this issue, it is very useful information.   However, this is not a core-v-verif issue, it is a cva6 issue.  Please close this issue and create a new one on the CVA6 repository.

Thanks!
