### ISSUE TITLE
Documentation: rvfi_trap size declaration

### ISSUE THREAD

**Issue by eroom1966** [openhwgroup/core-v-verif#1376]
in the documentation the rvfi_trap is documented as having width 14 bits  ([13:0])
however the declaration is 12 bits
    input logic [TRAP_WL-1:0]        rvfi_trap,
TRAP_WL is defined
localparam TRAP_WL          = 12;

so the declaration is
input logic [11:0]        rvfi_trap,

**Comment by Silabs-ArjanB** [comment]
@eroom1966 I transferred it

**Comment by Silabs-ArjanB** [comment]
@silabs-mateilga Could you please have a look at this?

**Comment by silabs-mateilga** [comment]
I'll have a look at this today.

**Comment by silabs-mateilga** [comment]
Fixed in PR [1378](https://github.com/openhwgroup/core-v-verif/pull/1378)

**Comment by MikeOpenHWGroup** [comment]
Can this issue be closed?

**Comment by eroom1966** [comment]
I took the PR and it looks like I have a width error generated - I posted on the PR

**Comment by silabs-mateilga** [comment]
Hmm, this is weird, it passed ci_check before merge. I'll have a look at it again tomorrow.

**Comment by eroom1966** [comment]
I think that is because it is only a warning - not an error

**Comment by silabs-mateilga** [comment]
Put in the effort and fixed the core of the issue this time, by changing to the struct used in the core.

https://github.com/openhwgroup/core-v-verif/pull/1380

**Comment by MikeOpenHWGroup** [comment]
Thanks @silabs-mateilga.  Back to you @eroom1966 - can this issue be closed?

**Comment by eroom1966** [comment]
yes I tested this and no more warnings - thx
