### ISSUE TITLE
remove references to core-v-verif/vendor_lib/imperas 

### ISSUE THREAD

**Issue by eroom1966** [openhwgroup/core-v-verif#1472]
@MikeOpenHWGroup @silabs-hfegran @silabs-mateilga 

I have a blocking issue due to the incorporation of libraries into the running simulator executable
This is due to the previous generation ISS integration loading an out of date library
in order to move forward I need any references removing, could somebody take the lead on this ?

**Comment by MikeOpenHWGroup** [comment]
@eroom1966 can you provide more information?

**Comment by eroom1966** [comment]
I think @silabs-hfegran is working on this but ...
There is a shared object in the vendor_lib/imperas which gets loaded 
This conflicts with a newer version.

The requirement here, is to remove all references to the code in vendor_lib/imperas - this can then be deleted and the problem goes away

**Comment by eroom1966** [comment]
Looks like this is now resolved thanks @silabs-hfegran
