### ISSUE TITLE
Script variable problem

### ISSUE THREAD

**Issue by guojiazhuxi** [openhwgroup/core-v-verif#1506]
## Bug Title
When verifying the Core-V-Verif Quick Start Guide article，Discover Error: UnrecoGnized OPCode `CSRW MTVEC, A0 ', Extension` ZICSR' Required error，Discovery after review，the $CFLAGS variable in ~/core-v-verif/mk/Makefile is not passed to ~/core-v-verif/cv32e40p/bsp/Makefile

是a中的p变量没有传递到c

### Type
Indicate whether the type of problem you found:
* Compile error (hopefully nobody has committed anything that doesn't compile!)

### Steps to Reproduce
Please provide:
![image](https://user-images.githubusercontent.com/49388283/203684043-ef82b988-1f8c-4699-8a40-03c8e3c8faf7.png)
![image](https://user-images.githubusercontent.com/49388283/203684066-86a66a74-fe3a-4189-a52e-d8ea791e4821.png)

**Comment by MikeOpenHWGroup** [comment]
Hi @guojiazhuxi, thanks for your issue.  I do not see this problem.  Could you provide me with your _exact_ commands starting from `git clone` and ending with `make...`?  It would also be helpful if you could attach anything written to stdout.

Thanks!

**Comment by pascalgouedo** [comment]
Hi @MikeOpenHWGroup,

This is all related to the last Embecosm toolchain (20221031) which now requires _zicsr in all march definitions.

Hi @guojiazhuxi 
CFLAGS value transmission between Common.mk and bsp Makefile seems to be incorrect.
The update you need right now is just to replace rv32imc by rv32imc_zicsr in bsp makefile.
We will manage to update the repo once another bunch of updates will be finished and pushed.

Regards.

**Comment by pascalgouedo** [comment]
Looks good as long as you stay in master branch ...

**Comment by guojiazhuxi** [comment]
> 

yes，the value CFLAGS should use export prefix

**Comment by MikeOpenHWGroup** [comment]
This issue was resolved in #1946
