### ISSUE TITLE
CV32E40X MISA Extension added for X

### ISSUE THREAD

**Issue by eroom1966** [openhwgroup/core-v-verif#1578]
@silabs-mateilga @MikeOpenHWGroup 
I notice that the setup for the Reference model when running ci_check has added in the X custom extension
is there a reason for this, because there are no custom extensions on the CV32E40X ?

**Comment by Silabs-ArjanB** [comment]
@eroom1966 WFE is a custom extension that is always present on both the 40X and 40S

**Comment by MikeOpenHWGroup** [comment]
[Link](https://docs.openhwgroup.org/projects/cv32e40x-user-manual/en/latest/instruction_set_extensions.html) to extension chapter in the E40X UM.
