### ISSUE TITLE
Secureseed0 does not return 0 upon a read

### ISSUE THREAD

**Issue by silabs-krdosvik** [openhwgroup/core-v-verif#1637]
## Secureseed0 does not return 0 upon a read
**Requirement:**
![image](https://user-images.githubusercontent.com/110398284/218060739-0bc17651-24fd-434e-898d-a69888158ad3.png)

**Test:**
![image](https://user-images.githubusercontent.com/110398284/218060764-873cd1c7-68bb-40e7-849c-aa288085a638.png)

### Type
Indicate whether the type of problem you found:
* Functionally incorrect behavior

### Steps to Reproduce
Please provide:
1. URL to branch that exhibits the issue: https://github.com/silabs-krdosvik/core-v-verif/tree/ISSproblem
(URL using hash: https://github.com/silabs-krdosvik/core-v-verif/tree/3ca6348ec45ba152f3d6fa870ff84979a1121d18)

3. Command line  (e.g. `make xrun-riscv-compliance`):
-	cd cv32e40s/sim/uvmt
- 	run test TEST=xsecure_test cfg=PMP
4. Logfile and/or wave-dump info (screen shots can be useful):
![image](https://user-images.githubusercontent.com/110398284/218061123-10fc212a-0e47-4bc3-9c55-1b622038db53.png)

### Additional context
Add any other context about the problem here:
The core output 0 when reading the secureseed0 CSR, while the ISS does not. According to the spec, read of the secureseed0 CSR should return 0.

@eroom1966

**Comment by eroom1966** [comment]
Thanks for the testcase - this looks like an early mistake where the register was defined as RW, but in the description that it always read 0
This later changed to WARL (0x0)
I have a fix I can commit shortly

**Comment by eroom1966** [comment]
This issue is fixed in the above PR

**Comment by eroom1966** [comment]
@silabs-krdosvik 
Can you please update/close the Issue with respect to the changes made to the modes
