### ISSUE TITLE
ISS: bit[0] of dpc should be hard-coded zero

### ISSUE THREAD

**Issue by silabs-hfegran** [openhwgroup/core-v-verif#1653]
### Context
![image](https://user-images.githubusercontent.com/75469886/219034549-1d1bfd91-622b-4185-8d6d-b6011b6b177b.png)

This bit is erroneously described as rw in the user manual (presumably the reason for the current reference model implementation), so there is a corresponding issue for updates to the user manual here: https://github.com/openhwgroup/cv32e40s/issues/407

RTL correctly implements this bit as hard-coded zero, and the user manual and ISS needs to be updated accordingly.

**Comment by silabs-hfegran** [comment]
Thanks for the update @eroom1966, I will leave this open until I have verified the fix.

**Comment by eroom1966** [comment]
@silabs-hfegran any update on this issue, I am pretty sure it is resolved

**Comment by silabs-hfegran** [comment]
No update yet, pending checks after PR #1702 gets merged - will update/close this issue accordingly

**Comment by silabs-hfegran** [comment]
This has been resolved, Thanks!
