### ISSUE TITLE
ISS: mseccfg writability with deconfigured PMP

### ISSUE THREAD

**Issue by silabs-hfegran** [openhwgroup/core-v-verif#1663]
User manual specifies the following: 
![image](https://user-images.githubusercontent.com/75469886/220100955-70a72521-fdb9-45a0-ae6e-c5211803836d.png)

CV32E40S cannot disable PMP, the existence of the PMP regions is unconditional, but their writability and legal values are controlled by the number of pmp-regions parameter in the core. Similarly, there needs to be a way to control the writability mask of mseccfg, as specified in the user manual. To my knowledge this register is currently always writeable as long as smepmp is enabled in the ISS, causing mismatches if one attempts to write to this register if there are no configured pmp regions. (In this case, the ISS is configured with 64 regions, but sets all pmpaddr and pmpcfg to always-zero)

**Comment by eroom1966** [comment]
Hi @silabs-hfegran 
Can you provide a testcase showing the issue.
To our knowledge, writability of mseccfg is already constrained as in the user manual.

**Comment by silabs-hfegran** [comment]
Duplicate of #1874
