### ISSUE TITLE
Update core-v-verif for CVA6 to support the latest riscv-arch-tests and its infrastructure.

### ISSUE THREAD

**Issue by Abdulwadoodd** [openhwgroup/core-v-verif#1919]
### Task Title
Update core-v-verif to support latest [riscv-arch-tests](https://github.com/riscv-non-isa/riscv-arch-test) infrastructure.

### Why we need an update
Currently core-v-verif supports a bit old version riscv-arch-test suites. We need to update it because:
- Generally, there are some fixes added to the existing tests, and test suites for more extensions are added (Bit Mnip (`B`), Double precision floating point (`D`), Single Precision floating point (`F`), some basic privilege). These tests suites are not supported by core-v-verif or at least not available these yaml files ([link](https://github.com/openhwgroup/core-v-verif/blob/cva6/dev/cva6/tests/testlist_riscv-arch-test-cv64a6_imafdc_sv39.yaml))
- The main reason for this update is to leverage the latest infrastructure of arch-tests which allows us to develop and run the privilege architecture tests. arch-tests now has a mechanism to support traps from S/U with and without Virtualization enabled (Related PRs: [[1]](https://github.com/riscv-non-isa/riscv-arch-test/pull/277), [[2]](https://github.com/riscv-non-isa/riscv-arch-test/pull/318)). This feature can be useful and leveraged in executing the virtual memory test plan (PR [here](https://github.com/openhwgroup/core-v-verif/pull/1789)) for the architectural testing and verification of the MMU of CVA6.

**Comment by MikeOpenHWGroup** [comment]
Hi @Abdulwadoodd, I believe this task is specific to the CVA6 only, is that correct?  If so, please edit the title to indicate that.

I have a few questions:
1. Is this task part of the CV32A60X v5.0.0 (step 1) verification effort?   If so, it should be tracked by @JeanRochCoulon.
2. There is currently no active CORE-V core supporting the double precision floating point ISA, and the current FPU IP in CVA6 is known to have many issues. Integration of the (as yet not fully verified) CVFPU is not planned for step 1 (v5.0.0).
3. Are there any features of CV32A60X v5.0.0 that require the updated riscv-arch-tests?
