### ISSUE TITLE
(Re) add features to VCS Makefile for CV32E40P

### ISSUE THREAD

**Issue by MikeOpenHWGroup** [openhwgroup/core-v-verif#2018]
As pointed out by @dd-vaibhavjain in #2014, there are few things in [vcs.mk](https://github.com/openhwgroup/core-v-verif/blob/309ac0c9ea81b0a2956e8b26d2cca754666b7403/mk/uvmt/vcs.mk#L1) which are removed we would like to add those things again.  Things like:
- FSDB=yes
- riscof setup,
- POST_TEST
- -full64 (vcs option)

**Comment by dd-vaibhavjain** [comment]
This issue can be closed now as all these changes are added back to vcs.mk for cv32e40p through the PR #2029 and merged successfully to cv32e40p/dev branch.
