### ISSUE TITLE
Questions Running Coremark Test 

### ISSUE THREAD

**Issue by nerdylye** [openhwgroup/core-v-verif#2185]
Hi, I am new to this and followed the tutorial steps to run coremark test on cv32w40p core. The simulation can be run but the output is a little weird because the iterations/sec is 0 and the coremark score does not show. May I know if it is supposed to be like this? 

The command I used to run is `make veri-test TEST=coremark` with Verilator version 5.012

The toolchain I used is from [RISC-V Compiler Toolchain - lowRISC provides a pre-built GCC based toolchain](https://github.com/lowRISC/lowrisc-toolchains/releases)

![image](https://github.com/openhwgroup/core-v-verif/assets/139537178/308eb7b5-2225-44fc-9a80-d34d4bb404f9)

**Comment by pascalgouedo** [comment]
Hi @nerdylye 
I think this is linked to your toolchain and if it is supporting to print Floating-Point or not.
For instance pre-built RISC-V toolchain used for CV32E40Pv1 were not containing anything to allow any printf of Floating-Point numbers (mainly because it implies much larger newlib library).

**Comment by pascalgouedo** [comment]
But you can still compute your Coremark/MHz score using the reported number of cycles (Total ticks).

**Comment by nerdylye** [comment]
Hi @MikeOpenHWGroup, thank you for your reply. I think I'm using CV32E40Pv1 because I do not see this branch `cv32e40p/dev` in my directory.

Hi @pascalgouedo, thank you for your reply. I see, so the simulation is running fine am I correct?


I also tried doing the same thing on CV32E40S and CV32E40X cores but both are not working. Is it because Verilator is not supported for these cores?

**Comment by pascalgouedo** [comment]
Hi @nerdylye  

Yes simulation is OK as confirmed by "Correct operation validated" sentence.

For core version you surely use cv32e40v2 RTL as I guess you are using master branch.

For the E40X and E40S I don't know.

**Comment by nerdylye** [comment]
I'm getting error like this for CV32E40S and CV32E40X cores, even when running hello-world test. 

![image](https://github.com/openhwgroup/core-v-verif/assets/139537178/efd5d496-3c57-494a-aecf-6a33882df7b3)

Who can I ask for assistance? Thank you

**Comment by MikeOpenHWGroup** [comment]
> I'm getting error like this for CV32E40S and CV32E40X cores, even when running hello-world test.

Hi @nerdylye, we like to keep GitHub Issues focused on a single topic.  Please open a second issue for this one.

**Comment by nerdylye** [comment]
Ok got it, thank you!
