### ISSUE TITLE
Unable to install python plugins

### ISSUE THREAD

**Issue by vidushiy25** [openhwgroup/core-v-verif#2271]
Hi, I am new to core-v-verif and I was trying to use the Quick start guide but when I try to install the python plug ins, I get the error: `Collecting pandas==1.3.4 (from -r requirements.txt (line 7))
  Could not find a version that satisfies the requirement pandas==1.3.4 (from -r requirements.txt (line 7)) (from versions: 0.1, 0.2, 0.3.0, 0.4.0, 0.4.1, 0.4.2, 0.4.3, 0.5.0, 0.6.0, 0.6.1, 0.7.0, 0.7.1, 0.7.2, 0.7.3, 0.8.0, 0.8.1, 0.9.0, 0.9.1, 0.10.0, 0.10.1, 0.11.0, 0.12.0, 0.13.0, 0.13.1, 0.14.0, 0.14.1, 0.15.0, 0.15.1, 0.15.2, 0.16.0, 0.16.1, 0.16.2, 0.17.0, 0.17.1, 0.18.0, 0.18.1, 0.19.0, 0.19.1, 0.19.2, 0.20.0, 0.20.1, 0.20.2, 0.20.3, 0.21.0, 0.21.1, 0.22.0, 0.23.0, 0.23.1, 0.23.2, 0.23.3, 0.23.4, 0.24.0, 0.24.1, 0.24.2, 0.25.0, 0.25.1, 0.25.2, 0.25.3, 1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.1.0, 1.1.1, 1.1.2, 1.1.3, 1.1.4, 1.1.5)
No matching distribution found for pandas==1.3.4 (from -r requirements.txt (line 7))
`
Also gives me a similar error for setuptools=65.5.1

I am guessing this is giving me the error: 
`File "/home/vy1g21/design/verif/bin/yaml2make", line 40, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'
Makefile:90: *** ERROR Could not find test.yaml for test: hello-world.  Stop.
`
How can I solve this?

**Comment by MikeOpenHWGroup** [comment]
Hi @vidushiy25, thanks for your interest in OpenHW and CORE-V-VERIF.  Unfortunately, we are not in a position to help people with issues related to your local computer installation.  I suggest you try "Dr. Google" for that.
