### ISSUE TITLE
Clarify new illegal handler code for HWLOOPs

### ISSUE THREAD

**Issue by MikeOpenHWGroup** [openhwgroup/core-v-verif#2286]
In pull-request #2280, the **corev-dv** function `cv32e40p_asm_program_gen::gen_illegal_instr_handler(int hart)` was substantially updated to add illegal handler code for HWLOOPs:
- If the illegal exception happened within a hwloop.
- If yes , check if the illegal was the last instruction of an hwloop with at least 1 more iteration left.
- If yes, then set MEPC to first instruction of hwloop instead of just incrementing by 4.
  Else MEPC is just incremented by 4.

The code is fine, but difficult for a human to follow (because it is SystemVerilog code that emits RISC-V assembler) so it would be good to add a comment header to the function to include the above information.

**Comment by MikeOpenHWGroup** [comment]
Hi @dd-vaibhavjain, is there a chance you can get to this Issue before the end of this calendar year?

**Comment by dd-vaibhavjain** [comment]
The relavant comments for hwloop handling were added for all the handlers in corev_dv for cv32e40p. 
This will be part of the next PR.

**Comment by MikeOpenHWGroup** [comment]
Hi @dd-vaibhavjain, has the "next PR" been submitted?

**Comment by XavierAubert** [comment]
Hi Mike ! 
PR #2357 has just been submitted, and it contains the commit 44647b9a6cbcb23519c534ce6177b5c22879123a to address this issue

**Comment by MikeOpenHWGroup** [comment]
Thanks @XavierAubert.  PR #2357 has been merged, so I will close this Issue.
