### ISSUE TITLE
ISS MISMATCH (minhv=1) mepc misalignment

### ISSUE THREAD

**Issue by silabs-krdosvik** [openhwgroup/core-v-verif#2333]
### Short explanation:

Running modified clic test “mret_with_minhv” (with induced error) and get this mismatch:
![image](https://github.com/openhwgroup/core-v-verif/assets/110398284/19db750d-a6f0-41ca-ba32-95bf91ad4d5c)

The core correctly clears the mepc lower bits to get XLEN/8 alignment, but at that address there is no instruction, causing the core to take an illegal instruction exception.

([https://github.com/riscv/riscv-fast-interrupt/blob/master/clic.adoc)](https://github.com/riscv/riscv-fast-interrupt/blob/master/clic.adoc)#) 
![image](https://github.com/openhwgroup/core-v-verif/assets/110398284/9b248212-8394-4283-9611-d69da860f77f)

### More detailed explanation:

**The problematic code:**
Test “mret_with_minhv” contains this code snippit:
![image](https://github.com/openhwgroup/core-v-verif/assets/110398284/ad21730f-78ae-4232-b5f4-af1946e37b49)

In the code snippit we see:
1)	That mcause gets the following values: minhv=1, mpp=0x3 and mpie=0.
2)	We store the address of label 1, which contain the address of label 2 (where an addi instruction is stored) to mepc (using the t0 register).
3)	Then, when running mret (and ignoring the fact that the address stored in mepc is forced misaligned), we would expect to run the instruction stored at the address stored in mepc, in other words the instruction stored in label 2 (addi).

**What is happening (by analysing the object dump):**

![image](https://github.com/openhwgroup/core-v-verif/assets/110398284/8402c1a8-505b-4d09-9793-4538ccadee1a)

-	We see step 1), 2) and 3) marked in the object dump.
-	We see that the address 6142 is stored in mepc, and we can see that the least significant bytes of address 6142 are 6246 (follow blue arrow).
-	By looking at the PC addresses shown in the object file we can illustrate the memory as follows:
![image](https://github.com/openhwgroup/core-v-verif/assets/110398284/da77916f-23ac-4eb3-aa05-4af9c59d4fd6)
-	When executing the mret the reference/iss execute the instruction at the address stored at 6142, which is 00_00_62_46 and contains a c.mv instruction. In the c code file we saw that lable 2 contained an addi instruction, we believe this is exchanged to an c.mv instruction by the compiler.

**Correct behavior:**
The clic spec states that we should clear the mepc lower bits to get XLEN/8 alignment. In our case that means that the core should execute the instruction stored at address 6140, 62460F0F. the core input 62460F0F gives an illegal instruction. 

### Type
* Functionally incorrect behavior

### Steps to Reproduce
1)	git clone [git@github.com:openhwgroup/core-v-verif.git](mailto:git@github.com:openhwgroup/core-v-verif.git)
2)	cd core-v-verif/
3)	git checkout cv32e40x/dev
4)	rm -rf cv32e40x
5)	git clone git@github.com:silabs-krdosvik/cv32e40x-dv.git cv32e40x
6)	cd cv32e40x
7)	git checkout clic-iss-problem
8)	cd sim/uvmt/
9)	make test TEST=clic CFG=clic_default

**Comment by eroom1966** [comment]
Hi Kristine,

Can I request that you run the simulation above, capturing the rvvi database.
In order to do this, you should only need to do the two following things

1. set environment variable in your shell
export IMPERAS_RVVI_DEBUG=1

2. add the following +define to your simulation run
+define+IDV_INCLUDE_TRACE2BIN

After running your simulation, you should have a directory called rvvi.db
Please provide this to me for analysis

**Comment by silabs-krdosvik** [comment]
Of course. 
I will send you an email with the rvvi.db folder.

**Comment by eroom1966** [comment]
@silabs-krdosvik 
Apologies in advance, the database produced is a little short - can I ask you to increase the number of MISMATCHES, so that the simulation continues for a few more cycles.
In my execution it exits exactly on the instruction here 

```
Info   mstatus 00001800 -> 00001880 [SD:0 XS:0(Off) FS:0(Off) MPP:3 VS:0(Off) MPIE:0->1 MIE:0]
Info   mcause 70390002 -> 78390002 [Interrupt:0 minhv:1 mpp:3 mpie:0->1 mpil:57 Code:2(Virtual supervisor software interrupt)]
Info (IDV) rvviDecode.rvvi_trace2log.process_event @ 1439630: RET,0,29212,00006132,"30200073 mret                   ",,,,CSR300(mstatus)=0000000000001880 CSR342(mcause)=0000000078390002,
Info (IDV) rvviDecode.rvvi_trace2log.process_event @ 1439650: EXC,0,29213,62460f0e,"0000     c.illegal              ",,,,CSR300(mstatus)=0000000000001800 CSR341(mepc)=0000000062460f0e CSR342(mcause)=0000000030390002,
rvviRefShutdown
```

Please increase the MISMATCHES to 100 and re-run
sorry for the inconvenience

thx
Lee

**Comment by silabs-krdosvik** [comment]
I see, of course, no problem. 

I will send you an email with the new version of the rvvi.db folder and also the xrun-clic.log file, which is what I believe is the full log (correct me if I am mistaken).

> Please increase the MISMATCHES to 100 

I have set the IDV_MAX_ERRORS parameter to 100 and now the ImperasDV VERIFICATION REPORT reports 33 mismatches instead of only 6. I tell you this in case I somehow have misunderstood and there was another parameter you wanted me to change.

(The new configuration additions are now merged to the branch "clic-iss-problem" on my cv32e40x-dv fork.)

**Comment by eroom1966** [comment]
Yes this sounds correct regarding the max errors
I am out of office till Jan/3, so will pick this up then

Thx
Lee

====================================================================
The information contained in this electronic mail message and any
attachments hereto
is privileged and confidential information intended only for the use of the
individual or
entity named above or their designee.  If the reader of this message is not
the intended
recipient, you are hereby notified that any dissemination, distribution or
copying of this
communication is strictly prohibited.  If you have received this
communication in error
please immediately notify us by return  message or by telephone and delete
the
original message from your mail system.  Thank you.
====================================================================

**Comment by silabs-krdosvik** [comment]
The MISMATCH disappears when updated our ISS version.

**Comment by eroom1966** [comment]
@silabs-krdosvik can we close this issue ?

**Comment by silabs-krdosvik** [comment]
Yes. the issue is closed.
