### ISSUE TITLE
[cv_dv_utils bp gen] Added a virtual sequence 

### ISSUE THREAD

**Issue by khandelwaltanuj** [openhwgroup/core-v-verif#2408]
Hello,

Back Pressure generator provides actually 4 sequences (no back pressure, heavy back pressure, occasional back pressure, mostly back pressure).  And user is supposed to write his/her own virtual sequence to be able to select randomly one of the back pressure sequence. 

In the new updated, a virtual sequence has been added to back pressure. The readme has been updated accordning. 

And it is being tested in the TB of HPDcache.

Thanks and regards
Tanuj Khandelwal

**Comment by MikeOpenHWGroup** [comment]
Hi @khandelwaltanuj, this sounds like an interesting update.  It is not clear to me why you are creating an Issue for this.  Reading your comment is seems that you are either announcing your plans to develop a BP generator or asking if this would be something the community would like to see.  In such cases, I would recommend posting a message to the [TWG:Verification channel on MatterMost](https://mattermost.openhwgroup.org/all-users/channels/twg--verification) and we can discuss it there.

When you are ready to make your contribution, please create a pull-request and be sure to follow the contribution guidelines detailed in #2407.
