### ISSUE TITLE
[BUG] : mstatus.TW is set to 1

### ISSUE THREAD

**Issue by AyoubJalali** [openhwgroup/core-v-verif#2467]
Hello, the [cv32a65x spec](https://docs.openhwgroup.org/projects/cva6-user-manual/06_cv32a65x_riscv/index.html#virt-control) the TW filed in MSTATUS is read-only zero, but Spike allow the read 1 in TW filed after a write into it in both modes TANDEM & SOLO

**Comment by MarioOpenHWGroup** [comment]
Can you share more info about the specific test and specific platform ?

**Comment by AyoubJalali** [comment]
> Can you share more info about the specific test and specific platform where you can see this issue ?

This issue based on the new [CV32A65X Spec](https://docs.openhwgroup.org/projects/cva6-user-manual/04_cv32a65x/riscv/priv.html#_machine_status_mstatus_and_mstatush_registers), and the issue appears using the csr_test, or just write a 0xffff_ffff and read it.

**Comment by zchamski** [comment]
Just checked Spike source (both "our" vendorized code and upstream master), and `mstatus.TW` is writable irrespective of implemented extensions `U`/`S`, whereas the `status.MPRV` bit is duly guarded by the presence of the `U` extension.

**Comment by zchamski** [comment]
@MarioOpenHWGroup: AFAI can tell, here too the features introduced in cvv #2445 should solve the issue (with proper mask, ideally derived from riscv-config info). Do you confirm?

**Comment by MarioOpenHWGroup** [comment]
The #2465 should give the mechanism to solve this yes :) But it should be configured in the cva6utils sv code
