### ISSUE TITLE
Spike doesn't raise exception on some debug CSRs

### ISSUE THREAD

**Issue by AyoubJalali** [openhwgroup/core-v-verif#2494]
Hello,
spike doens't raise an exception on some debug CSRs tdata1 & tdata2 & tdata3 / tselect and mcontext on the cv32a65x, even we don't support debug on this configuration.
The bug seen in solo and tandem mode on spike.

![image](https://github.com/openhwgroup/core-v-verif/assets/110232072/2da8d72f-0af9-436c-974e-913585070c1a)

**Comment by MarioOpenHWGroup** [comment]
test: unmapped_test 
testlist: testlist_csr_embedded.yaml

**Comment by AyoubJalali** [comment]
fixed due to PR cva6 #2407
