### ISSUE TITLE
Spike bug : minstret mismatch

### ISSUE THREAD

**Issue by AyoubJalali** [openhwgroup/core-v-verif#2525]
Hello, 
the bug appears on the tandem mode (solo mode we know this) on the minstret value in the CSR, the problem look like is rrelated to activated the Superscalar mode on the RTL side, so the instructions retired per cycle gonna change on the RTL side, and the spike tandem mode isn't aligned with that.

![image](https://github.com/user-attachments/assets/bf344952-c12b-4ecf-991a-82558d3ae7ce)

**Comment by MarioOpenHWGroup** [comment]
To double check

**Comment by AyoubJalali** [comment]
fixed due to PR cva6 #2407
