### ISSUE TITLE
License problem reported when run simulation

### ISSUE THREAD

**Issue by knightlv1989** [openhwgroup/core-v-verif#286]
Hi Mike

   I am a DV engineer from china. Now studying your RISCV verification testbench. I have gotten a OVPsim license from imperas. But when I run your uvmt_cv32 simulation with the license, problems report as following. Can you help me solve this problem.

Error (LIC_NE) License not available. FLEXLM reports:

No such feature exists.
Feature:       IMP_CPUMAN_MULTI
License path:  /database/projects/IPs/user/gqhu/RISCV_02/vendor_lib/imperas/OVPsim.lic:
FlexNet Licensing error:-5,357

No such feature exists.
Feature:       IMP_OVPSIM
License path:  /database/projects/IPs/user/gqhu/RISCV_02/vendor_lib/imperas/OVPsim.lic:
FlexNet Licensing error:-5,357

No such feature exists.
Feature:       IMP_OVPSIM_20200821
License path:  /database/projects/IPs/user/gqhu/RISCV_02/vendor_lib/imperas/OVPsim.lic:
FlexNet Licensing error:-5,357

Thanks

**Comment by MikeOpenHWGroup** [comment]
Hi @knightlv1989.

> I have gotten a OVPsim license from imperas. 

Which license do you have?   If you have the [free RISC-V Imperas ISS](https://www.imperas.com/riscvovpsim-free-imperas-riscv-instruction-set-simulator), then I do not think it will work. The CV32E40P verification environment uses a licensed version of the Imperas ISS.  You must either purchase the license or obtain an evaluation license from Imperas.  If you or your company joins the OpenHW Group, you may qualify for a free license.  If you are interested in learning more about OpenHW Group membership, please reach out to me at mike@openhwgroup.org.
