### ISSUE TITLE
Make rv32Zicsr and rv32Zifencei tests from the RISC-V compliance test suite part of the regression

### ISSUE THREAD

**Issue by Silabs-ArjanB** [openhwgroup/core-v-verif#313]
I see that we are not running the rv32Zicsr and rv32Zifencei test cases of the RISC-V compliance suite. Can they pelase be added to the following in core-v-verif/cv32/sim/uvmt_cv32/Makefile and be made part of the regression runs?

all_compliance: clone_compliance
	make build_compliance RISCV_ISA=rv32i   && \
	make build_compliance RISCV_ISA=rv32im  && \
	make build_compliance RISCV_ISA=rv32imc

**Comment by MikeOpenHWGroup** [comment]
All Compliance tests, including all rv32Zicsr tests and the rv32Zifencei test are integrated into the cv32_static_compliance_regression and passing in regression.
