### ISSUE TITLE
fatal error while running uvm testcase

### ISSUE THREAD

**Issue by Prarthi1703** [openhwgroup/core-v-verif#346]
# Template for CORE-V-VERIF Task Issues
Tasks are defined, assigned and tracked as GitHub Issues.  For obvious reasons,
the template for a task is very different from the template for a bug.

Please use this file as a template for creating Tasks to create or update any of
the documentation in this repository.
<br>**Hint**: click on the edit symbol (looks like a pencil) and then
edit the markdown source to create your issue.

## Task Title
A clear and concise description of the Task.  This can go in the titlebar.

### Task Outcome
Provide a brief description of what is expected.  For example, "Implement an
XYZ UVM Agent." If necessary point to a specification document.

### Background information
If necessary point to a specification in an outside document.

### Location Information
Specify the path, relative to the root of this GutHub project, of the code that
will be created and/or modified.

### Completion Criteria
Answer the question: how does the Assignee know they are done?

### Additional context
<img width="874" alt="license_error" src="https://user-images.githubusercontent.com/70278960/98519669-19038800-2297-11eb-94be-5663d4bcef4c.PNG">

**Comment by MikeOpenHWGroup** [comment]
Thanks for this issue @Prarthi1703.   As detailed in the README at [core-v-verif/cv32/sim/uvmt_cv32](https://github.com/openhwgroup/core-v-verif/tree/master/cv32/sim/uvmt_cv32#imperas-ovpsim-instruction-set-simulator), to use the UVM environment you need licenses for both a SystemVerilog simulator and the Imperas instruction set simulator.  We use the Imperas ISS as the reference model.

The instructions for obtaining an ISS license are embedded in the run-time message in your logfile.   You can reach out to me directly for help with that (mike \<at\> openhwgroup \<dot\> org).

It is possible to run the environment without the ISS by setting the USE_ISS Makefile variable to "NO".  This can be done via a shell variable or on the command-line:
```
make test TEST=<test_case_name> USE_ISS=NO
```
Keep in mind that most of of the testcases are not self checking, so without the ISS, the pass/fail criteria is meaningless.  Please refer to a discussion about self-checking vs. non-self-checking test-programs in the [Verification Strategy](https://core-v-docs-verif-strat.readthedocs.io/en/latest/sim_tests.html#test-program).
