### ISSUE TITLE
Facing issue while generating hex file

### ISSUE THREAD

**Issue by Prarthi1703** [openhwgroup/core-v-verif#366]
# Template for CORE-V-VERIF Task Issues
Tasks are defined, assigned and tracked as GitHub Issues.  For obvious reasons,
the template for a task is very different from the template for a bug.

Please use this file as a template for creating Tasks to create or update any of
the documentation in this repository.
<br>**Hint**: click on the edit symbol (looks like a pencil) and then
edit the markdown source to create your issue.

I am generating a hex file using the below command, but it is not generating the hex file properly and elf,objdump and readelf are getting generated.

$RISCV_BIN/riscv64-unknown-elf-gcc -g hello-world.c -o hello-world.o.
$RISCV_BIN/riscv32-unknown-elf-objcopy  -S -O ihex fibonacci.o fibonacci.hex
## Task Title
A clear and concise description of the Task.  This can go in the titlebar.

### Task Outcome
Provide a brief description of what is expected.  For example, "Implement an
XYZ UVM Agent." If necessary point to a specification document.

### Background information
If necessary point to a specification in an outside document.

### Location Information
Specify the path, relative to the root of this GutHub project, of the code that
will be created and/or modified.

### Completion Criteria
Answer the question: how does the Assignee know they are done?

**Comment by MikeOpenHWGroup** [comment]
Hi @Prarthi1703, this is a problem with the RISCV toolchain, not core-v-verif.  Please consult the appropriate GCC compiler/assembler documentation for generating hexfiles.
