### ISSUE TITLE
Please add "compliance" target to vcs.mk

### ISSUE THREAD

**Issue by MikeOpenHWGroup** [openhwgroup/core-v-verif#409]
Hi @masgia.  As of #406 the compliance regression has the ability to dump compliance test signatures and compare them to the reference signatures provided in compliance test-suite.   More information is available in the [UVM README](https://github.com/openhwgroup/core-v-verif/tree/master/cv32/sim/uvmt_cv32#risc-v-compliance-test-suite-and-regressions).

This update requires a simulator-specific `compliance` target to be added to each \<sim\>.mk   Can you add this for vcs.mk?   Check out xrun, dsim or vsim for a working example.

Thanks!

**Comment by masgia** [comment]
Hi,

OK, I'll add the feature

**Comment by MikeOpenHWGroup** [comment]
Thanks @masgia, I've merged in #415 so we are good to go.
