### ISSUE TITLE
Generate the project in windows

### ISSUE THREAD

**Issue by JackShanZemin** [openhwgroup/core-v-verif#440]
Hello 

I want to generate test case in windows enviroment, is it possible?

Best Regards
Jack

**Comment by MikeOpenHWGroup** [comment]
Hi @JackShanZemin.  The core-v-verif project does not explicitly support MS Windows and to date all of our development has been done using various flavors of Linux (CentOS, Debian and Ubuntu being the most popular of these).   As you've probably figured out already, core-v-verif supports two environments:

The "core testbench" is a minimalist environment that will get you up and running, but is not intended for complete verification of a CORE-V core.  The set-up required to run the core testbench is documented in its associated [README](https://github.com/openhwgroup/core-v-verif/blob/master/cv32/sim/core/README.md).  At a minimum you'll need Verilator (which can run under MS Windows via Cygwin) and a Windows build of the RISC-V toolchain and various Linux utilities such as "Make" and python which may also run under Cygwin.  A pre-built Windows version of the CORE-V specific toolchain is available [here](https://www.embecosm.com/resources/tool-chain-downloads/#corev).

Running the UVM environment has additional requirements as documented in its [README](https://github.com/openhwgroup/core-v-verif/blob/master/cv32/sim/uvmt_cv32/README.md).  For the UVM environment Verilator will not work.  For that you'll need a complete SystemVerilog simulator.  I believe, but do not know for sure, that Mentor's Questa runs under Windows.  You'll also need a Windows version of the Imperas Instruction Set Simulator.  Please reach out directly to Imperas about that.

So you are breaking new ground here.  Please let me know if there is anything I can do to help.  Keep in mind that like all open source projects, OpenHW projects are supported by the efforts of our members and contributors from the open source community.  If MS Windows support is something you'd like to see, you will need to help make that happen.

I believe this should answer your question so I will close this issue now.  If not, please feel free to re-open it.  If you would like to discuss this further, please reach out to me directly - my email address is on my public GitHub profile.
