### ISSUE TITLE
What is data value in objdump file

### ISSUE THREAD

**Issue by Prarthi1703** [openhwgroup/core-v-verif#443]
Hi,

I am running test for odd even number code in core-v-verif and understanding test flow

In objdump file I am enable to understand data value in instruction set
<img width="513" alt="objdump file" src="https://user-images.githubusercontent.com/70278960/104182081-e7916f00-5435-11eb-9794-2fa163b6dc2e.PNG">

**Comment by MikeOpenHWGroup** [comment]
Hi @Prarthi1703, thanks for your question.   The objdump is generated by the Toolchain.  So it is a tool used by OpenHW for core-v-verif, but not developed by OpenHW.  There is lots of good information about objdump online, including [this Wikipedia article](https://en.wikipedia.org/wiki/Objdump).

**Comment by Prarthi1703** [comment]
Hi Mike,

Thanks for responding.

My doubt is what is 6555 value meaning in objdump file
<img width="513" alt="objdump file" src="https://user-images.githubusercontent.com/70278960/104272003-3a186d00-54c2-11eb-8eb5-e75a94143ec2.PNG">

**Comment by MikeOpenHWGroup** [comment]
Hi @Prarthi1703, I _could_ tell you, but I am not a consultant for objdump users (and not a compiler toolchain expert in any case).   If you want to understand the output format of objdump (or any other component of the compiler toolchain), please consult the relevant documentation.
