### ISSUE TITLE
How to check Odd even number output in core-v-verif

### ISSUE THREAD

**Issue by pbhatt173** [openhwgroup/core-v-verif#445]
I am trying to run odd even number test written in C language  which will convert into hex file and check trying to understand objdump file  instruction.

So my doubt is how to check whether the number is odd or even in core
<img width="489" alt="a" src="https://user-images.githubusercontent.com/77604431/104912036-c4287000-59b1-11eb-851c-08cc4c3928f3.PNG">

**Comment by MikeOpenHWGroup** [comment]
This is a programming question, not a verification question and not a question about the core.  The core (in this case CV32E40P) will execute whatever program you write.   So your program must implement a function that determines whether or not an integer is odd or even.
