### ISSUE TITLE
How the core behave ?

### ISSUE THREAD

**Issue by prachi789** [openhwgroup/core-v-verif#446]
Hi ,

I have one doubt regarding Interrupt concept.

So my question is   suppose  currently my core is servicing machine timer interrupt but during this time if highest priority come then how the core and timers are behave ?

Means it terminates that interrupt execution (timer interrupt) or it hold for some time.

Thanks in advance.

**Comment by MikeOpenHWGroup** [comment]
Hi @prachi789, for questions about the integration and operation of the CV32E40P, please refer to the [CV32E40P User Manual](https://core-v-docs-verif-strat.readthedocs.io/projects/cv32e40p_um/en/latest/index.html).  I believe your question is directly addressed in the [nested interrupt and exception handling](https://core-v-docs-verif-strat.readthedocs.io/projects/cv32e40p_um/en/latest/exceptions_interrupts.html#nested-interrupt-exception-handling) sub-section of the Exceptions and Interrupts chapter.

If you cannot answer the question after reading the user manual, or the ISA please open an issue against the document.
