### ISSUE TITLE
How do I know whether Number is odd or even ?

### ISSUE THREAD

**Issue by prachi789** [openhwgroup/core-v-verif#449]
Hi ,

Currently I am running odd-even number testcase.
In C file I've added only printf function in if part as well as else part.
So my question is How to know Whether number is odd or even.

![image](https://user-images.githubusercontent.com/70278856/105963887-89a48e80-60a7-11eb-83ea-f3403d8aabdc.png)
![image](https://user-images.githubusercontent.com/70278856/105963986-a04ae580-60a7-11eb-861b-1ca21a83fde6.png)

**Comment by MikeOpenHWGroup** [comment]
Hi @prachi789, you are asking a programming theory question.  This is not a forum for that kind of discussion.  Issues created in this repository should be questions about the core-v-verif test-benches or suspected bugs in the test-bench code.

There are _many_ places you can go for an answer to you question, including [programiz](https://www.programiz.com/c-programming/examples/even-odd).   Please do not ask programming theory questions here.
