### ISSUE TITLE
showing don't care while running floating point example

### ISSUE THREAD

**Issue by pbhatt173** [openhwgroup/core-v-verif#467]
Hi,

I am running floating point example in below directory and I am getting dont care value in waveform
<img width="859" alt="1" src="https://user-images.githubusercontent.com/77604431/108058873-a74b8f00-707a-11eb-8c33-db9925716505.PNG">

Path : /home/pbhatt82/core-v-verif/core-v-cores/cv32e40p/example_tb/core
Command : make calculator-fp-vsim-run-gui

**Comment by MikeOpenHWGroup** [comment]
Hi @pbhatt173, as explained [here](https://cv32e40p.readthedocs.io/en/latest/integration/#parameters) in the CV32E40P User Manual, the floating point extension has not been verified.  It is not currently supported by core-v-verif and the target you are using is not supported by any of the Makefiles.
