### ISSUE TITLE
add EEMBC Coremark test

### ISSUE THREAD

**Issue by strichmo** [openhwgroup/core-v-verif#494]
### Task Outcome
The coremark suite is a general purpose processor benchmark and the below link is EEMBC's MCU version of it.  Similar to EMBench we should have a version of this running our the 40X and 40S with performance tracking.

https://github.com/eembc/coremark

### Completion Criteria
The benchmark executes on the 40X

**Comment by strichmo** [comment]
Robin Pedersen from Silicon Labs is working on this and will add the PR.

**Comment by MikeOpenHWGroup** [comment]
See my comments for issue #495.  They apply here as well.
