### ISSUE TITLE
port the cv32e40x compliance test to new framework

### ISSUE THREAD

**Issue by strichmo** [openhwgroup/core-v-verif#530]
### Task Outcome
The cv32e40x compliance tests and regression run with all supported extensions on the new compliance framework from riscv-arch-test

### Background information
The current implementation is a fork from the cv32e40p RTL freeze compliance state, which uses the old (v0.1) framework from riscv-compliance.  The implementation will be maintained in the short-term to enable compliance test operation during RTL development.

Note that there is a similar issue for cv32e40p as it should be ported as well.

### Completion Criteria
When feasible port the existing infrastructure to the new riscv-arch-test.
All extensions are tested in individual tests.
A suitable signature check is added.
A regression yaml that runs in Vmanager and Metrics is created and successfully runs all tests.

**Comment by silabs-hfegran** [comment]
Task out of date, any compliance/arch-test work should be targeting RISCOF
