### ISSUE TITLE
port the cv32e40p compliance tests to the new riscv-arch-test framework

### ISSUE THREAD

**Issue by strichmo** [openhwgroup/core-v-verif#531]
### Task Outcome
The cv32e40p compliance tests and regression run with all supported extensions on the new compliance framework from riscv-arch-test

### Background information
The current implementation (for v1.0.0 RTL freeze) uses the old (v0.1) framework from riscv-compliance.  The implementation will be maintained in the short-term to enable compliance test operation during RTL development.

Note that there is a similar issue for cv32e40x as it should be ported as well.

### Completion Criteria
When feasible port the existing infrastructure to the new riscv-arch-test.
All extensions are tested in individual tests.
A suitable signature check is added.
Non-applicable tests can be easily disregarded using the new riscv-arch-test framework.
A regression yaml that runs in Vmanager and Metrics is created and successfully runs all tests.

**Comment by MikeOpenHWGroup** [comment]
This work was completed as part of the CV32E40P v2 verification project and regression yamls exist for both [v1](https://github.com/openhwgroup/core-v-verif/blob/cv32e40p/dev/cv32e40p/regress/cv32e40p_v1_riscof_riscv_arch_test.yaml) and [v2](https://github.com/openhwgroup/core-v-verif/blob/cv32e40p/dev/cv32e40p/regress/cv32e40p_v2_riscof_riscv_arch_test.yaml).
