### ISSUE TITLE
Hello world for cv32e40x checks for e40p-specific CSRs

### ISSUE THREAD

**Issue by MikeOpenHWGroup** [openhwgroup/core-v-verif#587]
The `hello-world` test-program for CV32E40X is a direct copy of the version for CV32E40P.  That is fine, but the expected values for the `marchid` and perhaps `misa` CSRs must be updated to reflect the specified values.

### Steps to Reproduce
```
$ git clone git@github.com:openhwgroup/core-v-verif.git
$ cd core-v-verif/cv32e40x/sim/uvmt
$ make sanity SIMULATOR=<sim>
```
Where `sim` is specific to your set-up (e.g. xrun).

### Additional context
The test-program in questions is at `core-v-verif/cv32e40x/tests/programs/custom/hello-world/hello-world.c`.

It appears that the [CV32E40X User Manual](https://docs.openhwgroup.org/projects/cv32e40x-user-manual/control_status_registers.html#machine-implementation-id-mimpid) has been updated to reflect the new CSR values, but not the RTL.  As soon as you fix the test-program, you'll need to file a bug against the RTL.  :stuck_out_tongue_winking_eye:

**Comment by strichmo** [comment]
Closed as this is fixed.
