### ISSUE TITLE
RVFI UVM step and compare with interrupt and debug request

### ISSUE THREAD

**Issue by strichmo** [openhwgroup/core-v-verif#612]
### Task Outcome
The RVFI/RVVI implementation completed in this following issue properly supported interrupts and debug requests.
https://github.com/openhwgroup/core-v-verif/issues/611

### Completion Criteria
- The interrupt and debug request signaling is integrated into the RVVI interfaces.
- Existing E40P interrupt and debug tests pass on the E40X.  Any failures can be waived for purposes of this issue if they are related to RTL issues.

**Comment by MikeOpenHWGroup** [comment]
Another one to follow @JeanRochCoulon

**Comment by strichmo** [comment]
Scoreboard is running in wb_controller_e40x branch.
Old step and compare is removed and deprecated.
Temporary USE_RVVI flag is also deprecated as this mode of checking is now default.
