### ISSUE TITLE
rehost verification strategy document from core-v-docs to core-v-verif

### ISSUE THREAD

**Issue by strichmo** [openhwgroup/core-v-verif#649]
### Task Outcome
The source and scripting to support the current Verification Strategy Document is submitted to the core-v-verif repository and removed from the master branch of the 

### Background information
The current rendering of the Core-V Verification Strategy document is here: 
https://core-v-docs-verif-strat.readthedocs.io/en/latest/ 

### Location Information
The current source is here: 
https://github.com/openhwgroup/core-v-docs/tree/master/verif/Common/CORE-V_Verification_Strategy

### Completion Criteria
- The source and scripting are rehosted to the directory CORE-V_Verification_Strategy on the master branch of core-v-verif at the docs directory:
https://github.com/openhwgroup/core-v-verif/tree/master/docs
- The rendering of the documentation is enabled with the same web URL.
- Local Sphinx rendering continues to work as it currently does in core-v-docs.

**Comment by MikeOpenHWGroup** [comment]
Completed as of #670.  This task issue can be closed.
