### ISSUE TITLE
integrate the ISACOV functional coverage model to the CV32E40P

### ISSUE THREAD

**Issue by strichmo** [openhwgroup/core-v-verif#650]
### Task Outcome
Integrate the ISACOV coverage to the CV32E40P and measure functional coverage

### Background information
The ISACOV model is the next-generation functional ISA coverage model for the CV32E40X.  It is being developed on the E40X but should be applicable to any CORE-V core.
Once released to the cv32e40x/dev branch as the default coverage model for the E40X, the assignee of this task should apply it to the E40P.  This will also require a merge cycle to populate the cv32e40p/dev branch with the ISACOV model.

### Location Information
The ISACOV is here: https://github.com/openhwgroup/core-v-verif/tree/master/lib/uvm_agents/uvma_isacov

### Completion Criteria
The old functional coverage model is deprecated and removed.
The new ISACOV model is integrated and configured for the E40P.
Coverage reports are completed for the CV32E40P.

**Comment by MikeOpenHWGroup** [comment]
ISACOV was long ago integrated into all CORE-V-VERIF environments.    Note that users of ImperasDV may optionally use Imperas' ISA functional coverage model (closed source, not available in this repo.).
