### ISSUE TITLE
refresh debug vplan to 1.0.0 specification for cv32e40x

### ISSUE THREAD

**Issue by strichmo** [openhwgroup/core-v-verif#679]
### Task Outcome
The debug vplan is updated, reviewed and checked in for the E40X.

### Location Information
The vplan should be checked into the core-v-verif repository under the cv32e40x.  The updated vplan should replace the e40p vplan.

The cv32e40x will now support the debug 1.0.0 specification.  The vplan should be refreshed to ensure compliance to debug 1.0.0 features that will be implemented in cv32e40x.

### Completion Criteria
The testplan is updated and a satisfactory review meeting is held.

**Comment by silabs-robin** [comment]
Done.
I did the spec review and vplan update, with vplan review from the team.
The team fixed a whole bunch of new/old tests and added the link2cov.
