### ISSUE TITLE
use OBI memory agent in the CV32E40X testbench

### ISSUE THREAD

**Issue by strichmo** [openhwgroup/core-v-verif#681]
### Task Outcome
Merge the UVM OBI active memory agent into CV32E40X testbench.

### Background information
The mm_ram and all of its functionality should be replaced:
- Virtual peripherals
- Memory storage for I and D OBI busses

### Completion Criteria
The mm_ram is deprecated and all passing testing continue to pass.

**Comment by MikeOpenHWGroup** [comment]
Update.  @datum-dpoulin and I are actively working on the OBI memory agent. Currently the work is on the E40P, but this can be ported to E40X.

**Comment by silabs-hfegran** [comment]
@MikeOpenHWGroup Do you have a rough estimate on when the work for e40p will be ready?

**Comment by MikeOpenHWGroup** [comment]
Targeting end of this week.   The first release will not support PMA.

**Comment by strichmo** [comment]
The UVM OBI agent is now implemented and supported with this PR.  https://github.com/openhwgroup/core-v-verif/pull/774
The old OBI agent is now deprecated and removed from the cv32e40x testbench.

This will be merged to cv32e40x/dev shortly.
