### ISSUE TITLE
DSIM fails with heap messages with wb_controller_e40x branch

### ISSUE THREAD

**Issue by strichmo** [openhwgroup/core-v-verif#712]
### Type
DSIM run-time failure with interrupt_test and debug_test.  The test emits some heap memory message, then eventually core dumps.

### Steps to Reproduce
Run cv32e40x_ci_check_dev on the latest core-v-verif wb_controller_e40x branch.  
A run of this is already on-line on the Metrics database here:
https://openhwgroup.metrics.ca/main-core-v-verif-openhwgroup/results/testRuns/29c1ae98-c729-4526-af32-c4392db027ea

### Additional context
Some profiling clean-up was performed with Xcelium but no major issues were shown. 

The messages shown are:
GC Warning: Failed to expand heap by 16777216 bytes
GC Warning: Failed to expand heap by 16777216 bytes
GC Warning: Failed to expand heap by 16777216 bytes
GC Warning: Failed to expand heap by 262144 bytes
GC Warning: Out of Memory! Heap size: 4107 MiB. Returning NULL!
=F:[Signal] Received fatal signal 11 - likely null handle dereference.
GC Warning: Failed to expand heap by 16777216 bytes
GC Warning: Failed to expand heap by 262144 bytes
GC Warning: Out of Memory! Heap size: 4107 MiB. Returning NULL!
make: *** [/mux-flow/build/repo/mk/uvmt/dsim.mk:205: test] Segmentation fault (core dumped)

**Comment by MikeOpenHWGroup** [comment]
Just so everyone is aware: the recent merge of the `wb_controller_e40x` branch to `cv32e40x/dev` (#711) means that MetricsCI will fail.  This was a deliberate move to ensure the  `cv32e40x/dev` branch can continue to make progress.

**Comment by strichmo** [comment]
The issue was an assertion that was creating lots of threads in the antecedent of a concurrent property.  The property used a goto operator as it's very first clause.  This forces the simulator to spawn a thread at each clock edge, which can severely degrade resources on long simulations.

Fixed here by using repetition operators instead to force vacuous pass when condition not present.
https://github.com/openhwgroup/cv32e40x/pull/142
