### ISSUE TITLE
CV32E40X, update MARCHID

### ISSUE THREAD

**Issue by silabs-oivind** [openhwgroup/core-v-verif#714]
https://github.com/openhwgroup/cv32e40x/pull/134 updates the CV32E40X MARCHID to 20. Update core-v-verif accordingly when PR is merged.

**Comment by strichmo** [comment]
PR issued to fix

**Comment by silabs-hfegran** [comment]
I added another PR that fixes some outstanding ones

**Comment by strichmo** [comment]
All PRs should be merged and RTL pointer advanced.
