### ISSUE TITLE
add random gnt assertion to the OBI memory model

### ISSUE THREAD

**Issue by strichmo** [openhwgroup/core-v-verif#759]
### Task Outcome
The OBI memory model (i.e. the new UVM agent) should be able to randomly assert gnt to exercise OBI protocol in that gnt can be randomly asserted at any time regardless of req state.  This functionality however should not violate the slv_gnt latency knobs present in the configuration of the OBI agent.

### Location Information
Will be inserted on master as a hot fix in the lib/uvm_agents/uvma_obi_memory agent.

### Completion Criteria
Add a cover property to the OBI memory assertions to test for gnt assertion (and deassertion) in absence of req.

**Comment by silabs-robin** [comment]
This has been implemented quite some time ago.
