### ISSUE TITLE
vplan review for RV32 sequential execution of instructions

### ISSUE THREAD

**Issue by strichmo** [openhwgroup/core-v-verif#793]
### Task Outcome
Updated vplan coverage plan definition ISA RV32 instruction sequences.

### Background information
This review will update the coverage definition using the new ISACOV UVM coverage agent in all CORE-V testbenches.

### Location Information
The updated excel can be fetched from this branch:
https://github.com/strichmo/core-v-verif/blob/strichmo/pr/vplan_isacov_abz_etc/docs/VerifPlans/ISA/RV32/Simulation/RV32ISA_Sequential.xlsx

Note that the CV32E40X instruction group definition will also be reviewed as part of this review:
https://github.com/strichmo/core-v-verif/blob/strichmo/pr/vplan_isacov_abz_etc/cv32e40x/docs/VerifPlans/Simulation/micro_architecture/CV32E40X_Instruction_Groups.xlsx

### Completion Criteria
Vplan meeting is completed.
All action items completed
Vplan definition updated on master branch

**Comment by MikeOpenHWGroup** [comment]
Hi @strichmo, I took the liberty of stripping the templated title block from this issue.

**Comment by strichmo** [comment]
Reviewed and updated in this PR: https://github.com/openhwgroup/core-v-verif/pull/830
