### ISSUE TITLE
ci_check for cv32e40p/x is broken

### ISSUE THREAD

**Issue by eroom1966** [openhwgroup/core-v-verif#805]
@strichmo @MikeOpenHWGroup 
I have checked out a copy of the Master branch 814d170 and as far as I can se the ci_check for cv32e40p and cv32e40x no longer passes, it appears the debug_test is now failing reporting an illegal instruction

If I run debug_test standalone I get stuck with the following
makeuvmt test CV_CORE=cv32e40x TEST=debug_test

542610.000 ns: Illegal instruction (core 0) at PC 0x1a110800:

**Comment by strichmo** [comment]
Resolved the issue.  The ELF file for the debug_test needed to be rebuilt from clean.  The current dependencies for a firmware build do not handle flag changes in the Makefile.
