### ISSUE TITLE
add bitmanip extension to riscv-dv

### ISSUE THREAD

**Issue by strichmo** [openhwgroup/core-v-verif#923]
### Task Outcome
The Google riscv-dv project takes in one or multiple PRs to enable full coverage testing of the bitmanip extensions supported in CORE-V cores.

### Background information
Currently the Google riscv-dv project does support bitmanip instructions but only up to draft version 0p92.  For the CV32E40X and planned cores, this support needs to be extended to support the 1.0.0 frozen specification for zba, zbb, zbc, and zbs extensions.

### Location Information
Since these instructions are fundmental to riscv-dv and adding these to corev-dv would create a large amount of overriding, it is preferable to add the capability directly to riscv-dv.  This would require some coordination or questions with riscv-dv folks to ensure compliance to their standards of configuration of instructions, data structures, etc.  

### Completion Criteria
The PR(s) is/are accepted into riscv-dv and the hash for CV32E40X's riscv-dv pointer is successfully updated.  ci_check tests can run and a random test utilizing all supported zb* instructions is generated.

Note that the tool chains are also not completely compliant (gcc certainly is not).  There may be a requirement to add LLVM to the toolchain (or at least in a temporary fashion) to build a test with 1.0.0 bitmanip support.  (Currently experimental gccs only off 0.93 of zba,zbb, and zbc).

**Comment by silabs-hfegran** [comment]
Changes upstreamed to google, core-v-verif hash updated for 40x
