### ISSUE TITLE
Logical negation of class handles

### ISSUE THREAD

**Issue by MikeOpenHWGroup** [openhwgroup/core-v-verif#928]
In core-v-verif there are 51 violations of the linter's "Logical Violation" rule.  You are in the "assignees" list of this issue because git believes you authored one or more of these.

The Verissimo linter flags these as a [NON_STANDARD](https://dvteclipse.com/core5verif-verissimo/1/reports/run/1f430b7d805e2459f01c46e6ba58ef1dcbe59419/index.html?N4IgzgrgtlCGBOBPEAuAZrANmApgGhAGMALHQgazABV4ccBlHTMgFwEsB7AO1QFoBGAiTKUadRs0LtuVRAAccqAEwFibFtVgAjZhNaceKEAAYQq9Zp04A8vAAmOeKgDazwSFhhCIALp5nxgSe3j5-IGoaVNq6OAgkqCBmIA5eAAqwXEx6UgayCqiB4CywLBBgAGJsmCyOAGpYEIoo7sIUFVU18PWYjS4gAHLW_QD69FQAgv0AIuMASlO-BGhVOO3VdQ1NzmGEHFByCDizOHIc8CyV612bCUm7-4cAwvDqjmywl53dvSjbQrQlAxTEo4T4bHpNRJBLhcDjFaRcMHXCFgFzbHwAXyAA) violation.  The specific violation in question is using logical negation on operands of class handles.  The linter suggests using == null instead.

### Possible resolutions:
1. Accept the use of `if (!obj)` and create a project-wide waiver for the NON_STANDARD rule.
2. Convert all instances of `if (!obj)` to `if (obj == null)`.
3. Waive, or not, on a case-by-case basis.

### Steps to Reproduce
Lint checks are run every six hours - the link above will show all violations of this rule.

### Additional context
This is a set of linter issues identified by the [Verissimo SystemVerilog Testbench Linter](https://dvteclipse.com/products/verissimo-linter?gclid=CjwKCAjwzOqKBhAWEiwArQGwaNvs7iMGdFSyZ59goBb0s1ZJuvqTyaj4ZqcuLyBNA31qcqv8QvulVxoCHmEQAvD_BwE).  Please reach out to me directly if you have questions about the tool.

**Comment by datum-dpoulin** [comment]
@MikeCovrado not sure what I need to do. Didn't Steve already make the changes?

**Comment by datum-dpoulin** [comment]
Fix in PR #943

**Comment by datum-dpoulin** [comment]
Sorry about the delay, on it.

**Comment by MikeOpenHWGroup** [comment]
Resolved as of #1042
