### ISSUE TITLE
Incorrect makefile target for verilator hello world in core-v-verif/cv32/sim/core/readme.md

### ISSUE THREAD

**Issue by Smattacus** [openhwgroup/core-v-verif#98]
Section "Running your own C programs"  of [core-v-verif/cv32/sim/core/readme.md](https://github.com/openhwgroup/core-v-verif/tree/master/cv32/sim/core) points to a nonexistent makefile target for the verilator hello world. It appears it has been changed to "hello-world-veri-run" and using the target in the readme, "custom-veri-run," gives an error since it doesn't exist in the makefile.

I'll submit a pull request soon with a small fix for the readme for this.

**Comment by MikeOpenHWGroup** [comment]
Thanks for the catch Sean (@Smattacus) - much appreciated.   PR #99 has been merged in.
